name: Tests

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-versions: ["8.3", "8.2"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: "Create env file"
        run: |
          touch .env
          echo DB_CONNECTION="sqlite" >> .env
          echo DB_DATABASE=":memory:" >> .env
          echo PAYSTACK_PUBLIC_KEY=${{ secrets.PAYSTACK_PUBLIC_KEY }} >> .env
          echo PAYSTACK_SECRET_KEY=${{ secrets.PAYSTACK_SECRET_KEY }} >> .env
          cat .env

      - name: Run Migrations
        run: |
          php artisan migrate
          php artisan db:seed
          php artisan db:seed ConfigurationSeeder
          php artisan app:sync-roles

      - name: Tests
        run: composer test
