name: Tests

on: ["push", "pull_request"]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        container: ["8.3", "8.2"]

    container:
      image: "kirschbaumdevelopment/laravel-test-runner:8.3"

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: "Create env file"
        run: |
          cp .env.ci .env
          echo PAYSTACK_PUBLIC_KEY=${{ secrets.PAYSTACK_PUBLIC_KEY }} >> .env
          echo PAYSTACK_SECRET_KEY=${{ secrets.PAYSTACK_SECRET_KEY }} >> .env
          cat .env

      - name: Run Migrations
        run: |
          php artisan key:generate
          php artisan migrate
          php artisan db:seed
          php artisan db:seed ConfigurationSeeder
          php artisan app:sync-roles

      - name: Tests
        run: composer test
